name: Docs

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build docs
        run: yarn run docs
      
      - name: Publish docs
        run: |
          git config --global user.name 'Kyle Cutler'
          git config --global user.email 'kyle1320@users.noreply.github.com'
          git add docs
          git commit -m "Auto update documentation"
          git subtree push --prefix docs origin gh-pages
